"""empty message

Revision ID: a45e91aca545
Revises: 
Create Date: 2018-10-31 21:52:22.501876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45e91aca545'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rec_name', sa.String(length=100), nullable=False),
    sa.Column('prep_time', sa.String(length=50), nullable=True),
    sa.Column('cook_time', sa.String(length=50), nullable=True),
    sa.Column('rec_description', sa.Text(), nullable=False),
    sa.Column('rec_instruction', sa.Text(), nullable=False),
    sa.Column('ing_1', sa.String(length=50), nullable=False),
    sa.Column('ing_2', sa.String(length=50), nullable=True),
    sa.Column('ing_3', sa.String(length=50), nullable=True),
    sa.Column('ing_4', sa.String(length=50), nullable=True),
    sa.Column('ing_5', sa.String(length=50), nullable=True),
    sa.Column('ing_6', sa.String(length=50), nullable=True),
    sa.Column('ing_7', sa.String(length=50), nullable=True),
    sa.Column('ing_8', sa.String(length=50), nullable=True),
    sa.Column('ing_9', sa.String(length=50), nullable=True),
    sa.Column('ing_10', sa.String(length=50), nullable=True),
    sa.Column('minPrice', sa.Integer(), nullable=True),
    sa.Column('maxprice', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('fat', sa.String(length=10), nullable=True),
    sa.Column('cholesterol', sa.String(length=10), nullable=True),
    sa.Column('sodium', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('profilePic', sa.String(length=40), nullable=True),
    sa.Column('firstName', sa.String(length=20), nullable=True),
    sa.Column('lastName', sa.String(length=20), nullable=True),
    sa.Column('displayName', sa.String(length=20), nullable=True),
    sa.Column('cookingExperience', sa.String(length=12), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('postss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('link_current', sa.String(length=1000), nullable=True),
    sa.Column('content_current', sa.String(length=1000), nullable=True),
    sa.Column('post_type', sa.String(length=50), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postss')
    op.drop_table('users')
    op.drop_table('rec')
    op.drop_table('favs')
    # ### end Alembic commands ###
