"""empty message

Revision ID: ef15808f06b5
Revises: 
Create Date: 2018-11-01 22:17:51.923170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef15808f06b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fav_rec_name', sa.String(length=100), nullable=False),
    sa.Column('fav_prep_time', sa.String(length=50), nullable=True),
    sa.Column('fav_cook_time', sa.String(length=50), nullable=True),
    sa.Column('fav_rec_description', sa.Text(), nullable=False),
    sa.Column('fav_rec_instruction', sa.Text(), nullable=False),
    sa.Column('fav_ing1', sa.String(length=50), nullable=False),
    sa.Column('fav_ing2', sa.String(length=50), nullable=True),
    sa.Column('fav_ing3', sa.String(length=50), nullable=True),
    sa.Column('fav_ing4', sa.String(length=50), nullable=True),
    sa.Column('fav_ing5', sa.String(length=50), nullable=True),
    sa.Column('fav_ing6', sa.String(length=50), nullable=True),
    sa.Column('fav_ing7', sa.String(length=50), nullable=True),
    sa.Column('fav_ing8', sa.String(length=50), nullable=True),
    sa.Column('fav_ing9', sa.String(length=50), nullable=True),
    sa.Column('fav_ing10', sa.String(length=50), nullable=True),
    sa.Column('fav_minPrice', sa.Integer(), nullable=True),
    sa.Column('fav_maxPrice', sa.Integer(), nullable=True),
    sa.Column('fav_calories', sa.Integer(), nullable=True),
    sa.Column('fav_fat', sa.String(length=10), nullable=True),
    sa.Column('fav_cholestrol', sa.String(length=10), nullable=True),
    sa.Column('fav_sodium', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rec_name', sa.String(length=100), nullable=False),
    sa.Column('prep_time', sa.String(length=50), nullable=True),
    sa.Column('cook_time', sa.String(length=50), nullable=True),
    sa.Column('rec_description', sa.Text(), nullable=False),
    sa.Column('rec_instruction', sa.Text(), nullable=False),
    sa.Column('ing_1', sa.String(length=50), nullable=False),
    sa.Column('ing_2', sa.String(length=50), nullable=True),
    sa.Column('ing_3', sa.String(length=50), nullable=True),
    sa.Column('ing_4', sa.String(length=50), nullable=True),
    sa.Column('ing_5', sa.String(length=50), nullable=True),
    sa.Column('ing_6', sa.String(length=50), nullable=True),
    sa.Column('ing_7', sa.String(length=50), nullable=True),
    sa.Column('ing_8', sa.String(length=50), nullable=True),
    sa.Column('ing_9', sa.String(length=50), nullable=True),
    sa.Column('ing_10', sa.String(length=50), nullable=True),
    sa.Column('minPrice', sa.Integer(), nullable=True),
    sa.Column('maxprice', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('fat', sa.String(length=10), nullable=True),
    sa.Column('cholesterol', sa.String(length=10), nullable=True),
    sa.Column('sodium', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rec')
    op.drop_table('favs')
    # ### end Alembic commands ###
